name: ad_support_app
description: Ứng dụng Flutter hỗ trợ quảng cáo với AI chat
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # HTTP & API
  http: ^1.1.0
  
  # JSON
  json_annotation: ^4.8.1
  
  # Charts
  fl_chart: ^0.65.0
  
  # UI & Animations
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  equatable: ^2.0.5
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  
#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Regular.ttf
#        - asset: assets/fonts/Roboto-Bold.ttf
#          weight: 700

